theme: jekyll-theme-minimal
locale                   : "en-US"
title                    : "ENDALE LEGESSE" 
title_separator          : "-"
name                     : &name "HABTE ENDALE LEGESSE" 
description              : &description "personal description"
url                      : "https://endalelegesse.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "endalelegesse/endalelegesse.github.io"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
header_pages:
  - index.md
  - _pages/academic_background.md
  - _pages/research.md
  - _pages/publications.md
  - _pages/software_skills.md
  - _pages/portfolio.md
  - _pages/blogs.md
  - _pages/cv.md
